# Copyright 2022 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Paul Scheffler <paulsc@iis.ee.ethz.ch>

name: Set up environment

runs:
  using: composite
  steps:

  - uses: actions/setup-python@v2
    with:
      python-version: 3.9
      cache: pip

  - name: Install RISC-V GCC toolchain
    run: |
      curl -Ls -o riscv-gcc.tar.gz https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2022.06.10/riscv64-elf-ubuntu-20.04-nightly-2022.06.10-nightly.tar.gz
      sudo mkdir -p /tools/riscv && sudo chmod 777 /tools/riscv
      tar -C /tools/riscv -xf riscv-gcc.tar.gz --strip-components=1
      rm riscv-gcc.tar.gz
      echo "PATH=$PATH:/tools/riscv/bin" >> ${GITHUB_ENV}
    shell: bash

  - name: Install Bender
    run: |
      sudo mkdir -p /tools/bender && sudo chmod 777 /tools/bender
      cd /tools/bender && curl --proto '=https' --tlsv1.2 -sSf https://pulp-platform.github.io/bender/init | bash -s -- ${BENDER_VERSION}
      echo "PATH=$PATH:/tools/bender" >> ${GITHUB_ENV}
    env:
      BENDER_VERSION: 0.27.0
    shell: bash

  - name: Install Python requirements
    run: pip install -r .github/requirements.txt
    shell: bash
