# Copyright 2022 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Paul Scheffler <paulsc@iis.ee.ethz.ch>

name: build

on:
  push:
    branches: [ main, docker-ci ]
  pull_request:
    branches: [ main ]

jobs:

  # TODO: somehow handle reproducible boot ROM builds
  # TODO: migrate to and/or replicate on docker
  build-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Check if Dockerfile changed
        id: dockerfile
        uses: dorny/paths-filter@v2
        with:
          filters: |
            dockerfile:
              - '.github/Dockerfile'
      -
        name: Login to Docker Hub
        if: steps.dockerfile.outputs.dockerfile == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        if: steps.dockerfile.outputs.dockerfile == 'true'
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        if: steps.dockerfile.outputs.dockerfile == 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.github/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cheshire-ci:latest

  build:
    needs: build-docker
    strategy:
      matrix:
        target: [sw, hw, sim, xilinx]
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: pulpplatform/cheshire-ci:latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        name: Build target
        run: make ${{ matrix.target }}-all
      -
        name: Check whether clean
        run: git status && test -z "$(git status --porcelain --ignore-submodules)"
