# Copyright 2022 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Paul Scheffler <paulsc@iis.ee.ethz.ch>

name: gitlab-ci

on: [push, delete]

jobs:
  gitlab-ci:
    runs-on: ubuntu-latest
    steps:
    -
      name: Full checkout
      run: git clone --bare https://token:${{ github.token }}@github.com/${{ github.repository }} ${{ github.workspace }}
    -
      name: Push to mirror
      run: |
        git remote add gitlab https://token:${{ secrets.GITLAB_TOKEN }}@iis-git.ee.ethz.ch/github-mirror/cheshire.git
        git push --force --mirror gitlab
    - name: Check results
      # TODO: actually do this
      run: |
        curl --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" "https://iis-git.ee.ethz.ch/api/v4/projects/3478/pipelines"
